In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv("dataset.csv")

In [3]:
df.head()

Unit    2017_01  2017_01.1  2017_01.2  2017_01.3    2017_02  2017_02.1  \
0     1  15.883556       8530       1091       1741  16.992897       8549   
1     2  19.107819      11263       1007       1258  18.326892      11265   
2     3  14.831719       6537       1370        998  14.317025       6497   
3     4  14.689141       1090        138        319  14.236506       1081   
4     5  10.259615       1500         55        164  10.253614       1495   

   2017_02.2  2017_02.3    2017_03  ...  2017_10.3    2017_11  2017_11.1  \
0       1085       1728  14.241664  ...       1890  16.071489       8665   
1       1004       1259  17.253595  ...       1286  19.486698      11596   
2       1322       1086  13.618379  ...       1148  15.776422       6682   
3        139        327  12.937233  ...        361  13.737518       1044   
4         59        165  10.188065  ...        176  10.753049       1462   

   2017_11.2  2017_11.3    2017_12  2017_12.1  2017_12.2  2017_12.3  \
0        759       1938  15.178086       8614        766       1982   
1        748       1184  18.797653      11568        748       1212   
2        957       1266  15.112772       6624        942       1339   
3        145        358  13.765211       1019        150        378   
4         79        178  10.742230       1464         78        177   

      Revenue  
0  1033510000  
1  1406420000  
2   817470000  
3   119130000  
4   165090000  

[5 rows x 50 columns]

Preprocessing (Normalisasi MinMax Scaler lebih baik dari Standarisasi)

In [4]:
x = df.drop(['Unit', 'Revenue'], axis=1)
y = df.iloc[:, -1].values

# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
sc_y = StandardScaler()
x_ = sc_X.fit_transform(x)

# Reshape data karena hanya satu fitur
y_ = y.reshape(-1,1)
y_ = sc_y.fit_transform(y_)

In [5]:
x = df.drop(['Unit', 'Revenue'], axis=1)
y = df.iloc[:, -1].values 

from sklearn.preprocessing import MinMaxScaler

# define min max scaler
sc_X = MinMaxScaler()
sc_y = MinMaxScaler()
# transform data
x = sc_X.fit_transform(x)

# Reshape data karena hanya satu fitur
y = y.reshape(-1,1)
y = sc_y.fit_transform(y)
print(x)
print(y)

[[0.4378744  0.63469371 0.24215247 ... 0.64027474 0.24544863 0.95334295]
 [0.68422828 0.85296702 0.22331839 ... 0.86323496 0.23959688 0.58297258]
 [0.35750748 0.47552112 0.30470852 ... 0.49007472 0.3026658  0.64405964]
 ...
 [0.1770833  0.02579666 0.05313901 ... 0.05177749 0.04843953 0.1034151 ]
 [0.38829082 0.12682693 0.02533632 ... 0.15450223 0.013329   0.14333814]
 [0.22994929 0.07914703 0.00269058 ... 0.1015171  0.04258778 0.01250601]]
[[0.64944499]
 [0.88841375]
 [0.5110019 ]
 [0.06349059]
 [0.09294275]
 [0.03234667]
 [0.68811216]
 [0.48834886]
 [0.13785152]
 [0.32053052]
 [0.32004349]
 [0.34957255]
 [0.90699116]
 [0.12740613]
 [0.10582326]
 [0.1757433 ]
 [0.29376981]
 [0.17405794]
 [0.21438484]
 [0.36674016]
 [0.06881582]
 [0.14735491]
 [0.27186012]
 [0.05317977]
 [0.13885761]
 [0.10443268]
 [0.65284775]
 [0.9002305 ]
 [0.51958891]
 [0.06267675]
 [0.01118033]
 [0.01255169]
 [0.7198905 ]
 [0.51525696]
 [0.17380161]
 [0.33762764]
 [0.32491374]
 [0.41558999]
 [1.        ]
 [0.132199

Split Data

In [6]:
# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 0)

PEMODELAN

Decision Tree Regression


In [7]:
# Fitting Decision Tree Regression to the dataset
from sklearn.tree import DecisionTreeRegressor
regressorDT = DecisionTreeRegressor()
regressorDT.fit(X_train, y_train)

DecisionTreeRegressor()

In [8]:
# Predicting a test data

y_pred_ = regressorDT.predict(X_test)

print(y_pred_)
y_pred_1 = y_pred_.reshape(-1,1)
print(sc_y.inverse_transform(y_pred_1))

[0.05317977 0.61943774 0.1059322  0.22839147 0.41558999 0.14212016
 0.1757433  0.03234667 0.22839147 0.05317977 0.10582326 0.32004349
 0.48834886 0.32004349 0.03234667 0.14735491]
[[1.03040000e+08]
 [9.86683788e+08]
 [1.85360000e+08]
 [3.76457309e+08]
 [6.68580000e+08]
 [2.41831188e+08]
 [2.94300000e+08]
 [7.05300000e+07]
 [3.76457309e+08]
 [1.03040000e+08]
 [1.85190000e+08]
 [5.19480000e+08]
 [7.82120000e+08]
 [5.19480000e+08]
 [7.05300000e+07]
 [2.50000000e+08]]


In [9]:
from sklearn.metrics import r2_score

print("Mean absolute error: %.2f" % np.mean(np.absolute(y_pred_ - y_test)))
print("Residual sum of squares (MSE): %.2f" % np.mean((y_pred_ - y_test) ** 2))
print("R2-score: %.2f" % r2_score(y_pred_ , y_test) )

Mean absolute error: 0.21
Residual sum of squares (MSE): 0.08
R2-score: 0.69


Random Forest Regression


In [10]:
# Fitting Random Forest Regression to the dataset
from sklearn.ensemble import RandomForestRegressor
regressor = RandomForestRegressor(n_estimators = 100)
regressor.fit(X_train, y_train)

/tmp/ipykernel_67721/3293358574.py:4: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  regressor.fit(X_train, y_train)


RandomForestRegressor()

In [11]:
# Predicting a test result

y_pred_ = regressor.predict(X_test)

In [12]:
from sklearn.metrics import r2_score

print("Mean absolute error: %.2f" % np.mean(np.absolute(y_pred_ - y_test)))
print("Residual sum of squares (MSE): %.2f" % np.mean((y_pred_ - y_test) ** 2))
print("R2-score: %.2f" % r2_score(y_pred_ , y_test) )

Mean absolute error: 0.21
Residual sum of squares (MSE): 0.08
R2-score: 0.88


Regresi Linear Variabel Jamak

In [13]:
from sklearn import linear_model
regr = linear_model.LinearRegression()

regr.fit (X_train, y_train)
# The coefficients
print ('Coefficients: ', regr.coef_)
print ('Intercept: ',regr.intercept_)

Coefficients:  [[-1.08533588e-01 -9.76181189e-02  2.22138469e-01 -9.53853394e-01
   1.66762421e-02  9.55043332e-02 -8.50748139e-01  2.01724177e-01
  -3.35649218e-02 -1.56530211e+00  3.93059906e+00  2.31884092e-01
   1.56838230e-01  5.17534834e+00 -6.78836619e+00 -2.14897216e-01
  -2.88843021e-02 -1.28931874e+00  3.70962482e+00 -9.59094915e-01
  -2.34263344e-01 -6.23230405e-01  1.07014762e+00  6.07121744e-01
   1.88155563e-01 -8.63432327e-02 -5.65493820e-01  5.75574371e-01
   1.01395292e-01 -1.08804767e-02 -5.48672553e-01  1.11000917e-02
  -1.42222208e-01 -2.13122112e-01  4.24723656e-03  2.88850667e-01
  -2.82365595e-02 -1.88920348e-01  2.60304142e-01 -2.46936826e-01
   1.92050167e-01 -5.72037427e-01  8.65095711e-01  1.33547038e+00
  -7.06535392e-02  2.39542861e-01 -1.17266560e+00 -8.35645414e-01]]
Intercept:  [-0.01837985]


In [14]:
# Predicting a test data
y_pred_ = regr.predict(X_test)

In [15]:
from sklearn.metrics import r2_score
print("Mean absolute error: %.2f" % np.mean(np.absolute(y_pred_ - y_test)))
print("Residual sum of squares (MSE): %.2f" % np.mean((y_pred_ - y_test) ** 2))
print("R2-score: %.2f" % r2_score(y_pred_ , y_test) )

Mean absolute error: 0.06
Residual sum of squares (MSE): 0.01
R2-score: 0.91


Super Vector Reggression

In [16]:
# Fitting SVR to the dataset
from sklearn.svm import SVR
regressor_ = SVR(kernel = 'linear')
#linear = Linear Kernel
regressor_.fit(X_train, y_train)

/home/budosen/Downloads/voila/venv/lib/python3.8/site-packages/sklearn/utils/validation.py:985: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVR(kernel='linear')

In [17]:
# Predicting a test data

y_pred_ = regressor_.predict(X_test)
y_pred_1 = y_pred_.reshape(-1,1)
y_invers = sc_y.inverse_transform(y_pred_1) #untuk invers hasil prediksi ke bentuk asli
print(y_invers)

[[ 8.67721078e+06]
 [ 1.16554705e+09]
 [ 2.01992768e+07]
 [ 5.90585684e+08]
 [ 5.21966223e+08]
 [ 2.37376147e+08]
 [ 2.21994319e+08]
 [-8.82356066e+07]
 [ 3.36862479e+08]
 [-6.10396965e+07]
 [ 1.64661992e+08]
 [ 3.53091016e+08]
 [ 7.70735913e+08]
 [ 2.66711276e+08]
 [ 4.02660099e+07]
 [ 3.41316543e+08]]


In [18]:
from sklearn.metrics import r2_score

print("Mean absolute error: %.2f" % np.mean(np.absolute(y_pred_ - y_test)))
print("Residual sum of squares (MSE): %.2f" % np.mean((y_pred_ - y_test) ** 2))
print("R2-score: %.2f" % r2_score(y_pred_ , y_test) )

Mean absolute error: 0.23
Residual sum of squares (MSE): 0.09
R2-score: 0.90


SAVE MODEL

In [19]:
import pickle
# Save the Modle to file in the current working directory

Pkl_Filename = "model_regresi_linear2.pkl"  

with open(Pkl_Filename, 'wb') as file:  
    pickle.dump(regr, file)

In [20]:
# Load the Model back from file
with open(Pkl_Filename, 'rb') as file:  
    Pickled_LR_Model = pickle.load(file)

Pickled_LR_Model

LinearRegression()

In [21]:
# Use the Reloaded Model to 
# Calculate the accuracy score and predict target values

# Calculate the Score 
score = Pickled_LR_Model.score(X_test, y_test)  
# Print the Score
print("Test score: {0:.2f} %".format(100 * score))  

#********
#jika menggunakan data baru (X_test), maka perlu dinormalisasi dahulu X nya
#from sklearn.preprocessing import MinMaxScaler

#sc_X = MinMaxScaler()
#sc_y = MinMaxScaler()
#X_test = sc_X.fit_transform(X_test)
#*********


# Predict the Labels using the reloaded Model
Ypredict = Pickled_LR_Model.predict(X_test)  

y_invers = sc_y.inverse_transform(Ypredict) #untuk invers hasil prediksi ke bentuk asli
print(y_invers)


Test score: 89.18 %
[[ 2.96673729e+08]
 [ 1.47936824e+09]
 [ 2.15851681e+08]
 [ 5.09628611e+08]
 [ 6.30522596e+08]
 [ 2.82652326e+08]
 [ 6.74458448e+07]
 [-6.80681940e+07]
 [ 4.34237787e+08]
 [ 1.00813717e+08]
 [ 2.08316274e+08]
 [ 4.07681276e+08]
 [ 9.92950531e+08]
 [ 2.82894860e+08]
 [-1.46430099e+08]
 [ 3.69773046e+08]]
